version: 2

models:
  - name: stg_pipedrive__activity
    columns:
      - name: id
        tests:
          - not_null
      - name: activity_type
        tests:
          - relationships:
              to: ref('stg_pipedrive__activity_types')
              field: activity_type
      - name: user_id
        tests:
          - relationships:
              to: ref('stg_pipedrive__users')
              field: id
      - name: deal_id
        tests:
          - not_null
      - name: is_done
        tests:
          - not_null
      - name: due_time
        tests:
          - not_null
  - name: stg_pipedrive__deal_changes
    columns:
      - name: id
        tests:
          - not_null
      - name: change_time
        tests:
          - not_null
      - name: changed_field_key
        tests:
          - accepted_values:
              values: ['user_id', 'stage_id', 'lost_reason', 'add_time']
      - name: new_value
        tests:
          - not_null
  - name: stg_pipedrive__users
    columns:
      - name: id
        tests:
          - not_null
      - name: user_name
        tests:
          - not_null
      - name: user_email
        tests:
          - not_null
      - name: modified_time
        tests:
          - not_null
      