version: 2

sources:
  - name: postgres_public
    database: postgres
    schema: public
    tables:
      - name: activity
      - name: deal_changes
      - name: activity_types
      - name: fields
      - name: stages
      - name: users
